import React, { useState } from 'react';
import { VerificationResult } from '../types/verification';
import { Terminal, ChevronDown, ChevronUp, Code, Database, Clock } from 'lucide-react';

interface TechnicalDetailsProps {
  verification: VerificationResult;
}

export const TechnicalDetails: React.FC<TechnicalDetailsProps> = ({ verification }) => {
  const [isOpen, setIsOpen] = useState<boolean>(false);

  return (
    <div className="glass-panel rounded-2xl p-6 border-slate-800 border">
      <div
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center justify-between cursor-pointer select-none"
      >
        <div className="flex items-center gap-2.5">
          <div className="p-2 rounded-lg bg-slate-800 text-slate-400">
            <Terminal className="w-5 h-5" />
          </div>
          <div>
            <h3 className="font-bold text-sm text-slate-300">Technical Details & Pipeline Telemetry</h3>
            <span className="text-xs text-slate-500">Execution parameters, queries, deduplication clusters, and TTL metadata</span>
          </div>
        </div>

        <button className="p-1 rounded-lg text-slate-400 hover:text-slate-200">
          {isOpen ? <ChevronUp className="w-5 h-5" /> : <ChevronDown className="w-5 h-5" />}
        </button>
      </div>

      {isOpen && (
        <div className="space-y-4 pt-4 mt-4 border-t border-slate-800 text-xs">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <div className="p-3 bg-slate-900/60 rounded-xl border border-slate-800">
              <span className="text-slate-500 block mb-1">Verification ID</span>
              <span className="font-mono text-slate-300 select-all">{verification.id}</span>
            </div>
            <div className="p-3 bg-slate-900/60 rounded-xl border border-slate-800">
              <span className="text-slate-500 block mb-1">Session Working TTL</span>
              <span className="font-mono text-slate-300 flex items-center gap-1">
                <Clock className="w-3 h-3 text-amber-400" />
                20 Minutes Auto-Expire
              </span>
            </div>
            <div className="p-3 bg-slate-900/60 rounded-xl border border-slate-800">
              <span className="text-slate-500 block mb-1">Execution Mode</span>
              <span className="font-mono text-slate-300">
                {verification.is_demo_mode ? 'Demo Mode (Frozen Fixtures)' : 'Live Multi-API'}
              </span>
            </div>
          </div>

          <div>
            <span className="font-bold text-slate-400 block mb-2">Search Queries Generated by LLM:</span>
            <div className="flex flex-wrap gap-2">
              {verification.queries_used.map((q, idx) => (
                <span key={idx} className="px-2.5 py-1 rounded bg-slate-900 border border-slate-800 font-mono text-slate-300">
                  {q}
                </span>
              ))}
            </div>
          </div>

          <div>
            <span className="font-bold text-slate-400 block mb-2">Raw Pipeline JSON Payload:</span>
            <pre className="p-3 bg-slate-950 rounded-xl border border-slate-900 font-mono text-[11px] text-slate-400 overflow-x-auto max-h-60">
              {JSON.stringify({
                score_breakdown: verification.score_breakdown,
                source_summary: verification.source_analysis,
                date_analysis: verification.date_analysis
              }, null, 2)}
            </pre>
          </div>
        </div>
      )}
    </div>
  );
};
